language: node_js
node_js:
  - "10"
scripts:
  - yarn test
sudo: required
services:
  - docker
after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
